"""empty message

Revision ID: 132deb558f93
Revises: 859dc686c67a
Create Date: 2021-05-11 17:44:18.101675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132deb558f93'
down_revision = '859dc686c67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'precio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('precio', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
