"""empty message

Revision ID: 217dc66a7be1
Revises: 380a9a5eae61
Create Date: 2021-05-08 10:45:03.117637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217dc66a7be1'
down_revision = '380a9a5eae61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'precio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('precio', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
