"""empty message

Revision ID: 379fdfc667de
Revises: bc6b7d1c8108
Create Date: 2021-04-17 09:19:37.361413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379fdfc667de'
down_revision = 'bc6b7d1c8108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'propiedad', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propiedad', type_='foreignkey')
    op.drop_column('propiedad', 'user_id')
    # ### end Alembic commands ###
