"""empty message

Revision ID: 380a9a5eae61
Revises: 4d55fdea6b82
Create Date: 2021-05-04 17:27:46.587223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380a9a5eae61'
down_revision = '4d55fdea6b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('precio', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'precio')
    # ### end Alembic commands ###
