"""empty message

Revision ID: 3a59feff55ef
Revises: 6d03ecd0346d
Create Date: 2021-05-16 08:22:52.668484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a59feff55ef'
down_revision = '6d03ecd0346d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localidad'),
    sa.UniqueConstraint('localidad')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provincia'),
    sa.UniqueConstraint('provincia')
    )
    op.create_unique_constraint(None, 'amenidades', ['amenity'])
    op.add_column('propiedad', sa.Column('provincia_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'propiedad', 'provincias', ['provincia_id'], ['id'])
    op.drop_column('propiedad', 'provincia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('provincia', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'propiedad', type_='foreignkey')
    op.drop_column('propiedad', 'provincia_id')
    op.drop_constraint(None, 'amenidades', type_='unique')
    op.drop_table('provincias')
    op.drop_table('localidades')
    # ### end Alembic commands ###
