"""empty message

Revision ID: 48c7d6340a15
Revises: 86c1a525e5b6
Create Date: 2021-04-19 20:27:45.406688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c7d6340a15'
down_revision = '86c1a525e5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('provincia', sa.String(length=120), nullable=False))
    op.drop_column('propiedad', 'comunidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('comunidad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('propiedad', 'provincia')
    # ### end Alembic commands ###
