"""empty message

Revision ID: 670fd0a2945a
Revises: 9c4cf9b7c628
Create Date: 2021-04-14 16:46:44.245291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670fd0a2945a'
down_revision = '9c4cf9b7c628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('propiedad_aire_key', 'propiedad', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('propiedad_aire_key', 'propiedad', ['aire'])
    # ### end Alembic commands ###
