"""empty message

Revision ID: 78b78e151d2d
Revises: e0833b9bc373
Create Date: 2021-04-17 20:23:49.584728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b78e151d2d'
down_revision = 'e0833b9bc373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propiedad', 'camas',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('propiedad', 'codigo_postal',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('propiedad', 'dormitorios',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('propiedad', 'huespedes',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('propiedad', 'numero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('propiedad', 'numero',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('propiedad', 'huespedes',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('propiedad', 'dormitorios',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('propiedad', 'codigo_postal',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('propiedad', 'camas',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
