"""empty message

Revision ID: 859dc686c67a
Revises: ad5cc571107d
Create Date: 2021-05-11 16:49:49.455166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859dc686c67a'
down_revision = 'ad5cc571107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('huespedes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'huespedes')
    # ### end Alembic commands ###
