"""empty message

Revision ID: 86c1a525e5b6
Revises: e389b8220f0a
Create Date: 2021-04-19 19:10:56.726540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c1a525e5b6'
down_revision = 'e389b8220f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenidades', sa.Column('propiedad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'amenidades', 'propiedad', ['propiedad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'amenidades', type_='foreignkey')
    op.drop_column('amenidades', 'propiedad_id')
    # ### end Alembic commands ###
