"""empty message

Revision ID: 8755d25c5582
Revises: 48c7d6340a15
Create Date: 2021-04-21 09:04:20.539686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8755d25c5582'
down_revision = '48c7d6340a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provincias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provincia', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='provincias_pkey')
    )
    # ### end Alembic commands ###
