"""empty message

Revision ID: 905466c8f9e5
Revises: 3a59feff55ef
Create Date: 2021-05-16 11:35:13.634479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905466c8f9e5'
down_revision = '3a59feff55ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidades', sa.Column('provincia_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'localidades', 'provincias', ['provincia_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'localidades', type_='foreignkey')
    op.drop_column('localidades', 'provincia_id')
    # ### end Alembic commands ###
