"""empty message

Revision ID: 9c4cf9b7c628
Revises: ea7306602a01
Create Date: 2021-04-14 15:44:40.241668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4cf9b7c628'
down_revision = 'ea7306602a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('aire', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'propiedad', ['aire'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propiedad', type_='unique')
    op.drop_column('propiedad', 'aire')
    # ### end Alembic commands ###
