"""empty message

Revision ID: ae8b14b611d0
Revises: e7cb0a987535
Create Date: 2021-04-24 09:51:01.343090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8b14b611d0'
down_revision = 'e7cb0a987535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('titulo', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'titulo')
    # ### end Alembic commands ###
