"""empty message

Revision ID: b1ac5dfb78f4
Revises: 6dbf01c336f9
Create Date: 2021-04-17 10:57:52.031113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ac5dfb78f4'
down_revision = '6dbf01c336f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
