"""empty message

Revision ID: b3fa3fb4a4b0
Revises: 1055c3c8cc31
Create Date: 2021-06-02 17:19:55.869416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fa3fb4a4b0'
down_revision = '1055c3c8cc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amenidades_amenity_key', 'amenidades', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('amenidades_amenity_key', 'amenidades', ['amenity'])
    # ### end Alembic commands ###
