"""empty message

Revision ID: b6416d0ce575
Revises: 6e449f2071e4
Create Date: 2021-04-19 11:03:03.228896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6416d0ce575'
down_revision = '6e449f2071e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidades', sa.Column('ciudad', sa.String(length=120), nullable=False))
    op.drop_column('localidades', 'localidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidades', sa.Column('localidad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('localidades', 'ciudad')
    # ### end Alembic commands ###
