"""empty message

Revision ID: bc6b7d1c8108
Revises: ff1527af738b
Create Date: 2021-04-16 06:45:46.887617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6b7d1c8108'
down_revision = 'ff1527af738b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abrucena', sa.String(length=120), nullable=False),
    sa.Column('agua_amarga', sa.String(length=120), nullable=False),
    sa.Column('berja', sa.String(length=120), nullable=False),
    sa.Column('las_negras', sa.String(length=120), nullable=False),
    sa.Column('lucainena_de_las_torres', sa.String(length=120), nullable=False),
    sa.Column('mojacar', sa.String(length=120), nullable=False),
    sa.Column('rodalquilar', sa.String(length=120), nullable=False),
    sa.Column('velez_blanco', sa.String(length=120), nullable=False),
    sa.Column('arcos_de_la_frontera', sa.String(length=120), nullable=False),
    sa.Column('castellar_de_la_frontera', sa.String(length=120), nullable=False),
    sa.Column('chipiona', sa.String(length=120), nullable=False),
    sa.Column('grazalema', sa.String(length=120), nullable=False),
    sa.Column('medina_sidonia', sa.String(length=120), nullable=False),
    sa.Column('olvera', sa.String(length=120), nullable=False),
    sa.Column('sanlucar_de_barrameda', sa.String(length=120), nullable=False),
    sa.Column('vejer_de_la_frontera', sa.String(length=120), nullable=False),
    sa.Column('almodovar_del_rio', sa.String(length=120), nullable=False),
    sa.Column('baena', sa.String(length=120), nullable=False),
    sa.Column('espejo', sa.String(length=120), nullable=False),
    sa.Column('iznajar', sa.String(length=120), nullable=False),
    sa.Column('luque', sa.String(length=120), nullable=False),
    sa.Column('priego_de_cordoba', sa.String(length=120), nullable=False),
    sa.Column('zuheros', sa.String(length=120), nullable=False),
    sa.Column('albañuelas', sa.String(length=120), nullable=False),
    sa.Column('castril', sa.String(length=120), nullable=False),
    sa.Column('guadix', sa.String(length=120), nullable=False),
    sa.Column('montefrio', sa.String(length=120), nullable=False),
    sa.Column('nigüelas', sa.String(length=120), nullable=False),
    sa.Column('nivar', sa.String(length=120), nullable=False),
    sa.Column('pampaneira', sa.String(length=120), nullable=False),
    sa.Column('salobreña', sa.String(length=120), nullable=False),
    sa.Column('trevelez', sa.String(length=120), nullable=False),
    sa.Column('alcala_la_real', sa.String(length=120), nullable=False),
    sa.Column('alcaudete', sa.String(length=120), nullable=False),
    sa.Column('baeza', sa.String(length=120), nullable=False),
    sa.Column('baños_de_la_encima', sa.String(length=120), nullable=False),
    sa.Column('cazorla', sa.String(length=120), nullable=False),
    sa.Column('hornos', sa.String(length=120), nullable=False),
    sa.Column('la_iruela', sa.String(length=120), nullable=False),
    sa.Column('ubeda', sa.String(length=120), nullable=False),
    sa.Column('alajar', sa.String(length=120), nullable=False),
    sa.Column('almonaster_la_real', sa.String(length=120), nullable=False),
    sa.Column('ayamonte', sa.String(length=120), nullable=False),
    sa.Column('aracena', sa.String(length=120), nullable=False),
    sa.Column('el_rocio_almonte', sa.String(length=120), nullable=False),
    sa.Column('el_rompido', sa.String(length=120), nullable=False),
    sa.Column('jagubo', sa.String(length=120), nullable=False),
    sa.Column('moguer', sa.String(length=120), nullable=False),
    sa.Column('palos_de_frontera', sa.String(length=120), nullable=False),
    sa.Column('antequera', sa.String(length=120), nullable=False),
    sa.Column('archidona', sa.String(length=120), nullable=False),
    sa.Column('casares', sa.String(length=120), nullable=False),
    sa.Column('frigiliana', sa.String(length=120), nullable=False),
    sa.Column('marbella', sa.String(length=120), nullable=False),
    sa.Column('mijas', sa.String(length=120), nullable=False),
    sa.Column('nerja', sa.String(length=120), nullable=False),
    sa.Column('ojen', sa.String(length=120), nullable=False),
    sa.Column('ronda', sa.String(length=120), nullable=False),
    sa.Column('aznalcazar', sa.String(length=120), nullable=False),
    sa.Column('carmona', sa.String(length=120), nullable=False),
    sa.Column('cazalla_de_la_sierra', sa.String(length=120), nullable=False),
    sa.Column('constatina', sa.String(length=120), nullable=False),
    sa.Column('ecija', sa.String(length=120), nullable=False),
    sa.Column('estepa', sa.String(length=120), nullable=False),
    sa.Column('lebrija', sa.String(length=120), nullable=False),
    sa.Column('marchena', sa.String(length=120), nullable=False),
    sa.Column('osuna', sa.String(length=120), nullable=False),
    sa.Column('sanlucar_la_mayor', sa.String(length=120), nullable=False),
    sa.Column('santiponce', sa.String(length=120), nullable=False),
    sa.Column('utrera', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('almeria', sa.String(length=120), nullable=False),
    sa.Column('cadiz', sa.String(length=120), nullable=False),
    sa.Column('cordoba', sa.String(length=120), nullable=False),
    sa.Column('granada', sa.String(length=120), nullable=False),
    sa.Column('huelva', sa.String(length=120), nullable=False),
    sa.Column('jaen', sa.String(length=120), nullable=False),
    sa.Column('malaga', sa.String(length=120), nullable=False),
    sa.Column('sevilla', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provincias')
    op.drop_table('localidades')
    # ### end Alembic commands ###
