"""empty message

Revision ID: bf881344ab01
Revises: de8bee969dc7
Create Date: 2021-04-14 10:57:42.301170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf881344ab01'
down_revision = 'de8bee969dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('huelva', sa.Integer(), nullable=False),
    sa.Column('jaen', sa.Boolean(), nullable=False),
    sa.Column('cadiz', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provincias')
    # ### end Alembic commands ###
