"""empty message

Revision ID: ca411f72cb0c
Revises: 78b78e151d2d
Create Date: 2021-04-19 10:41:48.808153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca411f72cb0c'
down_revision = '78b78e151d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provincias', sa.Column('provincia', sa.String(length=120), nullable=False))
    op.drop_column('provincias', 'sevilla')
    op.drop_column('provincias', 'huelva')
    op.drop_column('provincias', 'granada')
    op.drop_column('provincias', 'jaen')
    op.drop_column('provincias', 'malaga')
    op.drop_column('provincias', 'cordoba')
    op.drop_column('provincias', 'almeria')
    op.drop_column('provincias', 'cadiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provincias', sa.Column('cadiz', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('almeria', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('cordoba', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('malaga', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('jaen', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('granada', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('huelva', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('provincias', sa.Column('sevilla', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('provincias', 'provincia')
    # ### end Alembic commands ###
