"""empty message

Revision ID: cb04e208a8b6
Revises: c23627f71360
Create Date: 2021-04-21 09:05:31.853518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb04e208a8b6'
down_revision = 'c23627f71360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('amenidades_id', sa.Integer(), nullable=True))
    op.drop_constraint('association_right_id_fkey', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'amenidades', ['amenidades_id'], ['id'])
    op.drop_column('association', 'right_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key('association_right_id_fkey', 'association', 'amenidades', ['right_id'], ['id'])
    op.drop_column('association', 'amenidades_id')
    # ### end Alembic commands ###
