"""empty message

Revision ID: d6c0fbde4824
Revises: b6416d0ce575
Create Date: 2021-04-19 11:08:24.624009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c0fbde4824'
down_revision = 'b6416d0ce575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidades', sa.Column('localidad', sa.String(length=120), nullable=False))
    op.drop_column('localidades', 'ciudad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidades', sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('localidades', 'localidad')
    # ### end Alembic commands ###
