"""empty message

Revision ID: d91afbebe8dc
Revises: e55327796107
Create Date: 2021-04-26 18:37:01.836316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91afbebe8dc'
down_revision = 'e55327796107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('codigo_postal', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'codigo_postal')
    # ### end Alembic commands ###
