"""empty message

Revision ID: de8bee969dc7
Revises: f04a85b587a3
Create Date: 2021-04-13 21:29:57.595360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8bee969dc7'
down_revision = 'f04a85b587a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propiedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=120), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('codigo_postal', sa.Integer(), nullable=False),
    sa.Column('comunidad', sa.String(length=120), nullable=False),
    sa.Column('dormitorios', sa.Integer(), nullable=False),
    sa.Column('huespedes', sa.Integer(), nullable=False),
    sa.Column('camas', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propiedad')
    # ### end Alembic commands ###
