"""empty message

Revision ID: dee68f015d5f
Revises: 905466c8f9e5
Create Date: 2021-05-16 14:13:45.098330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee68f015d5f'
down_revision = '905466c8f9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('localidad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'propiedad', 'localidades', ['localidad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propiedad', type_='foreignkey')
    op.drop_column('propiedad', 'localidad_id')
    # ### end Alembic commands ###
