"""empty message

Revision ID: e0f9c3622f20
Revises: e6ea358b85de
Create Date: 2021-04-15 19:41:23.572834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f9c3622f20'
down_revision = 'e6ea358b85de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'bathrooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('bathrooms', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
