"""empty message

Revision ID: e144345aba90
Revises: dee68f015d5f
Create Date: 2021-05-16 14:15:54.282365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e144345aba90'
down_revision = 'dee68f015d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'ciudad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
