"""empty message

Revision ID: e389b8220f0a
Revises: d6c0fbde4824
Create Date: 2021-04-19 18:44:25.464388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e389b8220f0a'
down_revision = 'd6c0fbde4824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localidades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('localidad', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='localidades_pkey')
    )
    # ### end Alembic commands ###
