"""empty message

Revision ID: e55327796107
Revises: e58afcab98bc
Create Date: 2021-04-26 18:36:34.959101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55327796107'
down_revision = 'e58afcab98bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedad', 'codigo_postal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('codigo_postal', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
