"""empty message

Revision ID: e6ea358b85de
Revises: 670fd0a2945a
Create Date: 2021-04-15 05:18:45.888466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ea358b85de'
down_revision = '670fd0a2945a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piscina', sa.Boolean(), nullable=False),
    sa.Column('cocina', sa.Boolean(), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('tv', sa.Boolean(), nullable=False),
    sa.Column('aire_acondicionado', sa.Boolean(), nullable=False),
    sa.Column('calefaccion', sa.Boolean(), nullable=False),
    sa.Column('chimenea', sa.Boolean(), nullable=False),
    sa.Column('agua_caliente', sa.Boolean(), nullable=False),
    sa.Column('zona_trabajo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('propiedad', 'aire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedad', sa.Column('aire', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('amenidades')
    # ### end Alembic commands ###
