"""empty message

Revision ID: ea5898f13601
Revises: 8d8f15e175fd
Create Date: 2021-05-16 14:44:01.540848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5898f13601'
down_revision = '8d8f15e175fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propiedad', 'provincia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('propiedad', 'localidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propiedad', 'localidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('propiedad', 'provincia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
