"""empty message

Revision ID: ea7306602a01
Revises: bf881344ab01
Create Date: 2021-04-14 11:45:40.874658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7306602a01'
down_revision = 'bf881344ab01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provincias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('huelva', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jaen', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cadiz', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='provincias_pkey')
    )
    # ### end Alembic commands ###
