"""empty message

Revision ID: f04a85b587a3
Revises: e08e1f962d99
Create Date: 2021-04-12 17:27:08.991913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04a85b587a3'
down_revision = 'e08e1f962d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=254), nullable=True))
    op.create_unique_constraint(None, 'user', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
